packages:
  - apps/*
  - packages/*

catalog:
  '@cloudflare/vite-plugin': ^1.13.12
  '@cloudflare/vitest-pool-workers': ^0.6.16
  '@cloudflare/workers-types': ^4.20251011.0
  '@react-router/cloudflare': ^7.9.3
  '@react-router/dev': ^7.9.3
  '@react-router/fs-routes': ^7.9.3
  '@sentry/cloudflare': ^8.40.0
  '@sentry/vite-plugin': ^2.22.6
  '@types/node': ^20.19.0
  '@types/react': ^18.2.20
  '@types/react-dom': ^18.2.7
  '@typescript-eslint/eslint-plugin': ^6.7.4
  '@typescript-eslint/parser': ^6.7.4
  autoprefixer: ^10.4.19
  eslint: ^8.38.0
  eslint-import-resolver-typescript: ^3.6.1
  eslint-plugin-import: ^2.28.1
  eslint-plugin-jsx-a11y: ^6.7.1
  eslint-plugin-react: ^7.33.2
  eslint-plugin-react-hooks: ^4.6.0
  fast-xml-parser: ^4.5.1
  isbot: ^4.1.0
  nanoid: ^5.0.9
  postcss: ^8.4.38
  react: ^18.2.0
  react-dom: ^18.2.0
  react-router: ^7.9.3
  tailwindcss: ^4.0.0
  typescript: ^5.9.3
  vite: ^7
  vite-tsconfig-paths: ^4.2.1
  vitest: 2.1.8
  wrangler: ^4.42.2
