// Generated by Wrangler on Sat Nov 23 2024 17:20:54 GMT+0100 (Central European Standard Time)
// by running `wrangler types`

interface Env {
	SENTRY_DSN: string;
	SENTRY_ENVIRONMENT: string;
	SENTRY_ENABLED: string;
}
