// Generated by Wrangler by running `wrangler types`

interface Env {
	GOOGLE_CLIENT_ID: "706944365506-45j0lthq4dc27i4jr05lplp6npdrrllj.apps.googleusercontent.com";
	SENTRY_DSN: string;
	SENTRY_ENVIRONMENT: string;
	SENTRY_ENABLED: string;
	GOOGLE_CLIENT_SECRET: string;
	BASE_URL: string;
	DB: D1Database;
}
