#:schema node_modules/wrangler/config-schema.json
name = "straumur"
compatibility_date = "2025-01-21"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./build/client"

[vars]
GOOGLE_CLIENT_ID="706944365506-45j0lthq4dc27i4jr05lplp6npdrrllj.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET=""
BASE_URL="https://straumur.app"
SESSION_SECRET=""

[[d1_databases]]
binding = "DB"
database_name = "straumur"
database_id = "57f4b23e-60cf-4f9f-9e82-1bdf41471533"
migrations_dir = "./../../migrations/"
