name: "Deploy Update Feeds"

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'apps/update-feeds/**'
      - 'packages/**'
      - '.github/workflows/deploy-update-feeds.yml'

env:
  CLOUDFLARE_ENV: "production"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build:update-feeds

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
          workingDirectory: apps/update-feeds
          wranglerVersion: "4"
          packageManager: pnpm

